// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface CanceledSalesMovieGetAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CanceledSalesMovieGetAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .SalesMovie salesMovie = 1;</code>
   */
  java.util.List<com.cinemaoperations.SalesMovie> 
      getSalesMovieList();
  /**
   * <code>repeated .SalesMovie salesMovie = 1;</code>
   */
  com.cinemaoperations.SalesMovie getSalesMovie(int index);
  /**
   * <code>repeated .SalesMovie salesMovie = 1;</code>
   */
  int getSalesMovieCount();
  /**
   * <code>repeated .SalesMovie salesMovie = 1;</code>
   */
  java.util.List<? extends com.cinemaoperations.SalesMovieOrBuilder> 
      getSalesMovieOrBuilderList();
  /**
   * <code>repeated .SalesMovie salesMovie = 1;</code>
   */
  com.cinemaoperations.SalesMovieOrBuilder getSalesMovieOrBuilder(
      int index);
}
