// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface CanceledSalesMovieGetAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CanceledSalesMovieGetAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
