// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

/**
 * Protobuf type {@code CardInfo}
 */
public  final class CardInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CardInfo)
    CardInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CardInfo.newBuilder() to construct.
  private CardInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CardInfo() {
    id_ = 0L;
    cardOwnerName_ = "";
    cardNumber_ = 0L;
    expiration_ = 0L;
    cvv_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CardInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cardOwnerName_ = s;
            break;
          }
          case 24: {

            cardNumber_ = input.readInt64();
            break;
          }
          case 32: {

            expiration_ = input.readInt64();
            break;
          }
          case 40: {

            cvv_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cinemaoperations.Cinema.internal_static_CardInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cinemaoperations.Cinema.internal_static_CardInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cinemaoperations.CardInfo.class, com.cinemaoperations.CardInfo.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int CARD_OWNER_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object cardOwnerName_;
  /**
   * <code>string card_owner_name = 2;</code>
   */
  public java.lang.String getCardOwnerName() {
    java.lang.Object ref = cardOwnerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardOwnerName_ = s;
      return s;
    }
  }
  /**
   * <code>string card_owner_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCardOwnerNameBytes() {
    java.lang.Object ref = cardOwnerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardOwnerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARD_NUMBER_FIELD_NUMBER = 3;
  private long cardNumber_;
  /**
   * <code>int64 card_number = 3;</code>
   */
  public long getCardNumber() {
    return cardNumber_;
  }

  public static final int EXPIRATION_FIELD_NUMBER = 4;
  private long expiration_;
  /**
   * <code>int64 expiration = 4;</code>
   */
  public long getExpiration() {
    return expiration_;
  }

  public static final int CVV_FIELD_NUMBER = 5;
  private long cvv_;
  /**
   * <code>int64 cvv = 5;</code>
   */
  public long getCvv() {
    return cvv_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getCardOwnerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cardOwnerName_);
    }
    if (cardNumber_ != 0L) {
      output.writeInt64(3, cardNumber_);
    }
    if (expiration_ != 0L) {
      output.writeInt64(4, expiration_);
    }
    if (cvv_ != 0L) {
      output.writeInt64(5, cvv_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getCardOwnerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cardOwnerName_);
    }
    if (cardNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, cardNumber_);
    }
    if (expiration_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, expiration_);
    }
    if (cvv_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, cvv_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cinemaoperations.CardInfo)) {
      return super.equals(obj);
    }
    com.cinemaoperations.CardInfo other = (com.cinemaoperations.CardInfo) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getCardOwnerName()
        .equals(other.getCardOwnerName());
    result = result && (getCardNumber()
        == other.getCardNumber());
    result = result && (getExpiration()
        == other.getExpiration());
    result = result && (getCvv()
        == other.getCvv());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + CARD_OWNER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCardOwnerName().hashCode();
    hash = (37 * hash) + CARD_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCardNumber());
    hash = (37 * hash) + EXPIRATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpiration());
    hash = (37 * hash) + CVV_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCvv());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cinemaoperations.CardInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.CardInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.CardInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.CardInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.CardInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.CardInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.CardInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.CardInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.CardInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.CardInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.CardInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.CardInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cinemaoperations.CardInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CardInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CardInfo)
      com.cinemaoperations.CardInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cinemaoperations.Cinema.internal_static_CardInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cinemaoperations.Cinema.internal_static_CardInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cinemaoperations.CardInfo.class, com.cinemaoperations.CardInfo.Builder.class);
    }

    // Construct using com.cinemaoperations.CardInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      cardOwnerName_ = "";

      cardNumber_ = 0L;

      expiration_ = 0L;

      cvv_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cinemaoperations.Cinema.internal_static_CardInfo_descriptor;
    }

    @java.lang.Override
    public com.cinemaoperations.CardInfo getDefaultInstanceForType() {
      return com.cinemaoperations.CardInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.cinemaoperations.CardInfo build() {
      com.cinemaoperations.CardInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cinemaoperations.CardInfo buildPartial() {
      com.cinemaoperations.CardInfo result = new com.cinemaoperations.CardInfo(this);
      result.id_ = id_;
      result.cardOwnerName_ = cardOwnerName_;
      result.cardNumber_ = cardNumber_;
      result.expiration_ = expiration_;
      result.cvv_ = cvv_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cinemaoperations.CardInfo) {
        return mergeFrom((com.cinemaoperations.CardInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cinemaoperations.CardInfo other) {
      if (other == com.cinemaoperations.CardInfo.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getCardOwnerName().isEmpty()) {
        cardOwnerName_ = other.cardOwnerName_;
        onChanged();
      }
      if (other.getCardNumber() != 0L) {
        setCardNumber(other.getCardNumber());
      }
      if (other.getExpiration() != 0L) {
        setExpiration(other.getExpiration());
      }
      if (other.getCvv() != 0L) {
        setCvv(other.getCvv());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cinemaoperations.CardInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cinemaoperations.CardInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object cardOwnerName_ = "";
    /**
     * <code>string card_owner_name = 2;</code>
     */
    public java.lang.String getCardOwnerName() {
      java.lang.Object ref = cardOwnerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardOwnerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string card_owner_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCardOwnerNameBytes() {
      java.lang.Object ref = cardOwnerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardOwnerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string card_owner_name = 2;</code>
     */
    public Builder setCardOwnerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardOwnerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string card_owner_name = 2;</code>
     */
    public Builder clearCardOwnerName() {
      
      cardOwnerName_ = getDefaultInstance().getCardOwnerName();
      onChanged();
      return this;
    }
    /**
     * <code>string card_owner_name = 2;</code>
     */
    public Builder setCardOwnerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardOwnerName_ = value;
      onChanged();
      return this;
    }

    private long cardNumber_ ;
    /**
     * <code>int64 card_number = 3;</code>
     */
    public long getCardNumber() {
      return cardNumber_;
    }
    /**
     * <code>int64 card_number = 3;</code>
     */
    public Builder setCardNumber(long value) {
      
      cardNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 card_number = 3;</code>
     */
    public Builder clearCardNumber() {
      
      cardNumber_ = 0L;
      onChanged();
      return this;
    }

    private long expiration_ ;
    /**
     * <code>int64 expiration = 4;</code>
     */
    public long getExpiration() {
      return expiration_;
    }
    /**
     * <code>int64 expiration = 4;</code>
     */
    public Builder setExpiration(long value) {
      
      expiration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 expiration = 4;</code>
     */
    public Builder clearExpiration() {
      
      expiration_ = 0L;
      onChanged();
      return this;
    }

    private long cvv_ ;
    /**
     * <code>int64 cvv = 5;</code>
     */
    public long getCvv() {
      return cvv_;
    }
    /**
     * <code>int64 cvv = 5;</code>
     */
    public Builder setCvv(long value) {
      
      cvv_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 cvv = 5;</code>
     */
    public Builder clearCvv() {
      
      cvv_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CardInfo)
  }

  // @@protoc_insertion_point(class_scope:CardInfo)
  private static final com.cinemaoperations.CardInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cinemaoperations.CardInfo();
  }

  public static com.cinemaoperations.CardInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CardInfo>
      PARSER = new com.google.protobuf.AbstractParser<CardInfo>() {
    @java.lang.Override
    public CardInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CardInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CardInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CardInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cinemaoperations.CardInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

