// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface CardInfoGetAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CardInfoGetAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .CardInfo cardInfo = 1;</code>
   */
  java.util.List<com.cinemaoperations.CardInfo> 
      getCardInfoList();
  /**
   * <code>repeated .CardInfo cardInfo = 1;</code>
   */
  com.cinemaoperations.CardInfo getCardInfo(int index);
  /**
   * <code>repeated .CardInfo cardInfo = 1;</code>
   */
  int getCardInfoCount();
  /**
   * <code>repeated .CardInfo cardInfo = 1;</code>
   */
  java.util.List<? extends com.cinemaoperations.CardInfoOrBuilder> 
      getCardInfoOrBuilderList();
  /**
   * <code>repeated .CardInfo cardInfo = 1;</code>
   */
  com.cinemaoperations.CardInfoOrBuilder getCardInfoOrBuilder(
      int index);
}
