// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

/**
 * Protobuf type {@code CardInfoGetAllResponse}
 */
public  final class CardInfoGetAllResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CardInfoGetAllResponse)
    CardInfoGetAllResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CardInfoGetAllResponse.newBuilder() to construct.
  private CardInfoGetAllResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CardInfoGetAllResponse() {
    cardInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CardInfoGetAllResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              cardInfo_ = new java.util.ArrayList<com.cinemaoperations.CardInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            cardInfo_.add(
                input.readMessage(com.cinemaoperations.CardInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        cardInfo_ = java.util.Collections.unmodifiableList(cardInfo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cinemaoperations.Cinema.internal_static_CardInfoGetAllResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cinemaoperations.Cinema.internal_static_CardInfoGetAllResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cinemaoperations.CardInfoGetAllResponse.class, com.cinemaoperations.CardInfoGetAllResponse.Builder.class);
  }

  public static final int CARDINFO_FIELD_NUMBER = 1;
  private java.util.List<com.cinemaoperations.CardInfo> cardInfo_;
  /**
   * <code>repeated .CardInfo cardInfo = 1;</code>
   */
  public java.util.List<com.cinemaoperations.CardInfo> getCardInfoList() {
    return cardInfo_;
  }
  /**
   * <code>repeated .CardInfo cardInfo = 1;</code>
   */
  public java.util.List<? extends com.cinemaoperations.CardInfoOrBuilder> 
      getCardInfoOrBuilderList() {
    return cardInfo_;
  }
  /**
   * <code>repeated .CardInfo cardInfo = 1;</code>
   */
  public int getCardInfoCount() {
    return cardInfo_.size();
  }
  /**
   * <code>repeated .CardInfo cardInfo = 1;</code>
   */
  public com.cinemaoperations.CardInfo getCardInfo(int index) {
    return cardInfo_.get(index);
  }
  /**
   * <code>repeated .CardInfo cardInfo = 1;</code>
   */
  public com.cinemaoperations.CardInfoOrBuilder getCardInfoOrBuilder(
      int index) {
    return cardInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < cardInfo_.size(); i++) {
      output.writeMessage(1, cardInfo_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < cardInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, cardInfo_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cinemaoperations.CardInfoGetAllResponse)) {
      return super.equals(obj);
    }
    com.cinemaoperations.CardInfoGetAllResponse other = (com.cinemaoperations.CardInfoGetAllResponse) obj;

    boolean result = true;
    result = result && getCardInfoList()
        .equals(other.getCardInfoList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCardInfoCount() > 0) {
      hash = (37 * hash) + CARDINFO_FIELD_NUMBER;
      hash = (53 * hash) + getCardInfoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cinemaoperations.CardInfoGetAllResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.CardInfoGetAllResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.CardInfoGetAllResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.CardInfoGetAllResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.CardInfoGetAllResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.CardInfoGetAllResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.CardInfoGetAllResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.CardInfoGetAllResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.CardInfoGetAllResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.CardInfoGetAllResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.CardInfoGetAllResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.CardInfoGetAllResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cinemaoperations.CardInfoGetAllResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CardInfoGetAllResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CardInfoGetAllResponse)
      com.cinemaoperations.CardInfoGetAllResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cinemaoperations.Cinema.internal_static_CardInfoGetAllResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cinemaoperations.Cinema.internal_static_CardInfoGetAllResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cinemaoperations.CardInfoGetAllResponse.class, com.cinemaoperations.CardInfoGetAllResponse.Builder.class);
    }

    // Construct using com.cinemaoperations.CardInfoGetAllResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCardInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (cardInfoBuilder_ == null) {
        cardInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        cardInfoBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cinemaoperations.Cinema.internal_static_CardInfoGetAllResponse_descriptor;
    }

    @java.lang.Override
    public com.cinemaoperations.CardInfoGetAllResponse getDefaultInstanceForType() {
      return com.cinemaoperations.CardInfoGetAllResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.cinemaoperations.CardInfoGetAllResponse build() {
      com.cinemaoperations.CardInfoGetAllResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cinemaoperations.CardInfoGetAllResponse buildPartial() {
      com.cinemaoperations.CardInfoGetAllResponse result = new com.cinemaoperations.CardInfoGetAllResponse(this);
      int from_bitField0_ = bitField0_;
      if (cardInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          cardInfo_ = java.util.Collections.unmodifiableList(cardInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cardInfo_ = cardInfo_;
      } else {
        result.cardInfo_ = cardInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cinemaoperations.CardInfoGetAllResponse) {
        return mergeFrom((com.cinemaoperations.CardInfoGetAllResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cinemaoperations.CardInfoGetAllResponse other) {
      if (other == com.cinemaoperations.CardInfoGetAllResponse.getDefaultInstance()) return this;
      if (cardInfoBuilder_ == null) {
        if (!other.cardInfo_.isEmpty()) {
          if (cardInfo_.isEmpty()) {
            cardInfo_ = other.cardInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCardInfoIsMutable();
            cardInfo_.addAll(other.cardInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.cardInfo_.isEmpty()) {
          if (cardInfoBuilder_.isEmpty()) {
            cardInfoBuilder_.dispose();
            cardInfoBuilder_ = null;
            cardInfo_ = other.cardInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cardInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCardInfoFieldBuilder() : null;
          } else {
            cardInfoBuilder_.addAllMessages(other.cardInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cinemaoperations.CardInfoGetAllResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cinemaoperations.CardInfoGetAllResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.cinemaoperations.CardInfo> cardInfo_ =
      java.util.Collections.emptyList();
    private void ensureCardInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        cardInfo_ = new java.util.ArrayList<com.cinemaoperations.CardInfo>(cardInfo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cinemaoperations.CardInfo, com.cinemaoperations.CardInfo.Builder, com.cinemaoperations.CardInfoOrBuilder> cardInfoBuilder_;

    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public java.util.List<com.cinemaoperations.CardInfo> getCardInfoList() {
      if (cardInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cardInfo_);
      } else {
        return cardInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public int getCardInfoCount() {
      if (cardInfoBuilder_ == null) {
        return cardInfo_.size();
      } else {
        return cardInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public com.cinemaoperations.CardInfo getCardInfo(int index) {
      if (cardInfoBuilder_ == null) {
        return cardInfo_.get(index);
      } else {
        return cardInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public Builder setCardInfo(
        int index, com.cinemaoperations.CardInfo value) {
      if (cardInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCardInfoIsMutable();
        cardInfo_.set(index, value);
        onChanged();
      } else {
        cardInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public Builder setCardInfo(
        int index, com.cinemaoperations.CardInfo.Builder builderForValue) {
      if (cardInfoBuilder_ == null) {
        ensureCardInfoIsMutable();
        cardInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        cardInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public Builder addCardInfo(com.cinemaoperations.CardInfo value) {
      if (cardInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCardInfoIsMutable();
        cardInfo_.add(value);
        onChanged();
      } else {
        cardInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public Builder addCardInfo(
        int index, com.cinemaoperations.CardInfo value) {
      if (cardInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCardInfoIsMutable();
        cardInfo_.add(index, value);
        onChanged();
      } else {
        cardInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public Builder addCardInfo(
        com.cinemaoperations.CardInfo.Builder builderForValue) {
      if (cardInfoBuilder_ == null) {
        ensureCardInfoIsMutable();
        cardInfo_.add(builderForValue.build());
        onChanged();
      } else {
        cardInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public Builder addCardInfo(
        int index, com.cinemaoperations.CardInfo.Builder builderForValue) {
      if (cardInfoBuilder_ == null) {
        ensureCardInfoIsMutable();
        cardInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        cardInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public Builder addAllCardInfo(
        java.lang.Iterable<? extends com.cinemaoperations.CardInfo> values) {
      if (cardInfoBuilder_ == null) {
        ensureCardInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cardInfo_);
        onChanged();
      } else {
        cardInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public Builder clearCardInfo() {
      if (cardInfoBuilder_ == null) {
        cardInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cardInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public Builder removeCardInfo(int index) {
      if (cardInfoBuilder_ == null) {
        ensureCardInfoIsMutable();
        cardInfo_.remove(index);
        onChanged();
      } else {
        cardInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public com.cinemaoperations.CardInfo.Builder getCardInfoBuilder(
        int index) {
      return getCardInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public com.cinemaoperations.CardInfoOrBuilder getCardInfoOrBuilder(
        int index) {
      if (cardInfoBuilder_ == null) {
        return cardInfo_.get(index);  } else {
        return cardInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public java.util.List<? extends com.cinemaoperations.CardInfoOrBuilder> 
         getCardInfoOrBuilderList() {
      if (cardInfoBuilder_ != null) {
        return cardInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cardInfo_);
      }
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public com.cinemaoperations.CardInfo.Builder addCardInfoBuilder() {
      return getCardInfoFieldBuilder().addBuilder(
          com.cinemaoperations.CardInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public com.cinemaoperations.CardInfo.Builder addCardInfoBuilder(
        int index) {
      return getCardInfoFieldBuilder().addBuilder(
          index, com.cinemaoperations.CardInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .CardInfo cardInfo = 1;</code>
     */
    public java.util.List<com.cinemaoperations.CardInfo.Builder> 
         getCardInfoBuilderList() {
      return getCardInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cinemaoperations.CardInfo, com.cinemaoperations.CardInfo.Builder, com.cinemaoperations.CardInfoOrBuilder> 
        getCardInfoFieldBuilder() {
      if (cardInfoBuilder_ == null) {
        cardInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.cinemaoperations.CardInfo, com.cinemaoperations.CardInfo.Builder, com.cinemaoperations.CardInfoOrBuilder>(
                cardInfo_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        cardInfo_ = null;
      }
      return cardInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CardInfoGetAllResponse)
  }

  // @@protoc_insertion_point(class_scope:CardInfoGetAllResponse)
  private static final com.cinemaoperations.CardInfoGetAllResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cinemaoperations.CardInfoGetAllResponse();
  }

  public static com.cinemaoperations.CardInfoGetAllResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CardInfoGetAllResponse>
      PARSER = new com.google.protobuf.AbstractParser<CardInfoGetAllResponse>() {
    @java.lang.Override
    public CardInfoGetAllResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CardInfoGetAllResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CardInfoGetAllResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CardInfoGetAllResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cinemaoperations.CardInfoGetAllResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

