// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface CardInfoGetAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CardInfoGetAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
