// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface ChangedAllChangeledSalesMovieGetAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChangedAllChangeledSalesMovieGetAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isCanceled = 1;</code>
   */
  boolean getIsCanceled();
}
