// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface ChangedAllCanceledSalesMovieGetAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChangedAllCanceledSalesMovieGetAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
