// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface ChangedAllChangeledSalesMovieGetAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChangedAllChangeledSalesMovieGetAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
