// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public final class Cinema {
  private Cinema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Seat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Seat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SeatGetAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SeatGetAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SeatGetAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SeatGetAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SeatUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SeatUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SeatUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SeatUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieAmount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieAmount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieAmountGetAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieAmountGetAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieAmountGetAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieAmountGetAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieAmountUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieAmountUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieAmountUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieAmountUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieAmountInsertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieAmountInsertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieAmountInsertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieAmountInsertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieAmountDeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieAmountDeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovieAmountDeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovieAmountDeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SalesMovie_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SalesMovie_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SalesMovieGetAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SalesMovieGetAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SalesMovieGetAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SalesMovieGetAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SalesMovieInsertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SalesMovieInsertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SalesMovieInsertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SalesMovieInsertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SalesMovieDeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SalesMovieDeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SalesMovieDeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SalesMovieDeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SalesMovieCancelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SalesMovieCancelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SalesMovieCancelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SalesMovieCancelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CanceledSalesMovieGetAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CanceledSalesMovieGetAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CanceledSalesMovieGetAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CanceledSalesMovieGetAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangedAllCanceledSalesMovieGetAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangedAllCanceledSalesMovieGetAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChangedAllCanceledSalesMovieGetAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChangedAllCanceledSalesMovieGetAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteAllCanceledSalesMovieRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteAllCanceledSalesMovieRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteAllChangeledSalesMovieResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteAllChangeledSalesMovieResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CardInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CardInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CardInfoGetAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CardInfoGetAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CardInfoGetAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CardInfoGetAllResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Cinema.proto\"\'\n\004Seat\022\n\n\002id\030\001 \001(\003\022\023\n\013se" +
      "at_status\030\002 \001(\010\"\023\n\021SeatGetAllRequest\")\n\022" +
      "SeatGetAllResponse\022\023\n\004seat\030\001 \003(\0132\005.Seat\"" +
      "4\n\021SeatUpdateRequest\022\023\n\004seat\030\001 \001(\0132\005.Sea" +
      "t\022\n\n\002id\030\002 \001(\005\"\'\n\022SeatUpdateResponse\022\021\n\ti" +
      "sUpdated\030\001 \001(\010\"f\n\013MovieAmount\022\n\n\002id\030\001 \001(" +
      "\003\022\022\n\nmovie_name\030\002 \001(\t\022\016\n\006amount\030\003 \001(\003\022\023\n" +
      "\013expire_date\030\004 \001(\t\022\022\n\nmovie_time\030\005 \001(\003\"\032" +
      "\n\030MovieAmountGetAllRequest\">\n\031MovieAmoun" +
      "tGetAllResponse\022!\n\013movieAmount\030\001 \003(\0132\014.M" +
      "ovieAmount\"I\n\030MovieAmountUpdateRequest\022!" +
      "\n\013movieAmount\030\001 \001(\0132\014.MovieAmount\022\n\n\002id\030" +
      "\002 \001(\005\".\n\031MovieAmountUpdateResponse\022\021\n\tis" +
      "Updated\030\001 \001(\010\"=\n\030MovieAmountInsertReques" +
      "t\022!\n\013movieAmount\030\001 \001(\0132\014.MovieAmount\",\n\031" +
      "MovieAmountInsertResponse\022\017\n\007isSaved\030\001 \001" +
      "(\010\"&\n\030MovieAmountDeleteRequest\022\n\n\002id\030\001 \001" +
      "(\005\"-\n\031MovieAmountDeleteResponse\022\020\n\010isDel" +
      "ete\030\001 \001(\010\"\224\001\n\nSalesMovie\022\n\n\002id\030\001 \001(\003\022\022\n\n" +
      "movie_name\030\002 \001(\t\022\025\n\rcustomer_name\030\003 \001(\t\022" +
      "\022\n\nseat_count\030\004 \001(\003\022\023\n\013total_price\030\005 \001(\003" +
      "\022\023\n\013is_canceled\030\006 \001(\010\022\021\n\tsale_date\030\007 \001(\t" +
      "\"\031\n\027SalesMovieGetAllRequest\";\n\030SalesMovi" +
      "eGetAllResponse\022\037\n\nsalesMovie\030\001 \003(\0132\013.Sa" +
      "lesMovie\":\n\027SalesMovieInsertRequest\022\037\n\ns" +
      "alesMovie\030\001 \001(\0132\013.SalesMovie\"+\n\030SalesMov" +
      "ieInsertResponse\022\017\n\007isSaved\030\001 \001(\010\"%\n\027Sal" +
      "esMovieDeleteRequest\022\n\n\002id\030\001 \001(\005\",\n\030Sale" +
      "sMovieDeleteResponse\022\020\n\010isDelete\030\001 \001(\010\"%" +
      "\n\027SalesMovieCancelRequest\022\n\n\002id\030\001 \001(\005\".\n" +
      "\030SalesMovieCancelResponse\022\022\n\nisCanceled\030" +
      "\001 \001(\010\"!\n\037CanceledSalesMovieGetAllRequest" +
      "\"C\n CanceledSalesMovieGetAllResponse\022\037\n\n" +
      "salesMovie\030\001 \003(\0132\013.SalesMovie\"+\n)Changed" +
      "AllCanceledSalesMovieGetAllRequest\"@\n*Ch" +
      "angedAllCanceledSalesMovieGetAllResponse" +
      "\022\022\n\nisCanceled\030\001 \001(\010\"$\n\"DeleteAllCancele" +
      "dSalesMovieRequest\"C\n$DeleteAllChangeled" +
      "SalesMovieResponse\022\033\n\023isDeletedAllChange" +
      "d\030\001 \001(\010\"e\n\010CardInfo\022\n\n\002id\030\001 \001(\003\022\027\n\017card_" +
      "owner_name\030\002 \001(\t\022\023\n\013card_number\030\003 \001(\003\022\022\n" +
      "\nexpiration\030\004 \001(\003\022\013\n\003cvv\030\005 \001(\003\"\027\n\025CardIn" +
      "foGetAllRequest\"5\n\026CardInfoGetAllRespons" +
      "e\022\033\n\010cardInfo\030\001 \003(\0132\t.CardInfo2\205\t\n\027Cinem" +
      "aOperationsService\0227\n\nGetAllSeat\022\022.SeatG" +
      "etAllRequest\032\023.SeatGetAllResponse\"\000\022=\n\020U" +
      "pdateSeatStatus\022\022.SeatUpdateRequest\032\023.Se" +
      "atUpdateResponse\"\000\022L\n\021GetAllMovieAmount\022" +
      "\031.MovieAmountGetAllRequest\032\032.MovieAmount" +
      "GetAllResponse\"\000\022L\n\021UpdateMovieAmount\022\031." +
      "MovieAmountUpdateRequest\032\032.MovieAmountUp" +
      "dateResponse\"\000\022L\n\021InsertMovieAmount\022\031.Mo" +
      "vieAmountInsertRequest\032\032.MovieAmountInse" +
      "rtResponse\"\000\022L\n\021DeleteMovieAmount\022\031.Movi" +
      "eAmountDeleteRequest\032\032.MovieAmountDelete" +
      "Response\"\000\022C\n\016GetAllCardInfo\022\026.CardInfoG" +
      "etAllRequest\032\027.CardInfoGetAllResponse\"\000\022" +
      "I\n\020GetAllSalesMovie\022\030.SalesMovieGetAllRe" +
      "quest\032\031.SalesMovieGetAllResponse\"\000\022I\n\020In" +
      "sertSalesMovie\022\030.SalesMovieInsertRequest" +
      "\032\031.SalesMovieInsertResponse\"\000\022I\n\020DeleteS" +
      "alesMovie\022\030.SalesMovieDeleteRequest\032\031.Sa" +
      "lesMovieDeleteResponse\"\000\022I\n\020CancelSalesM" +
      "ovie\022\030.SalesMovieCancelRequest\032\031.SalesMo" +
      "vieCancelResponse\"\000\022a\n\030CanceledGetAllSal" +
      "esMovie\022 .CanceledSalesMovieGetAllReques" +
      "t\032!.CanceledSalesMovieGetAllResponse\"\000\022y" +
      "\n\034ChangedAllCanceledSalesMovie\022*.Changed" +
      "AllCanceledSalesMovieGetAllRequest\032+.Cha" +
      "ngedAllCanceledSalesMovieGetAllResponse\"" +
      "\000\022k\n\033deleteAllCanceledSalesMovie\022#.Delet" +
      "eAllCanceledSalesMovieRequest\032%.DeleteAl" +
      "lChangeledSalesMovieResponse\"\000B\030\n\024com.ci" +
      "nemaoperationsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Seat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Seat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Seat_descriptor,
        new java.lang.String[] { "Id", "SeatStatus", });
    internal_static_SeatGetAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SeatGetAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SeatGetAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_SeatGetAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SeatGetAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SeatGetAllResponse_descriptor,
        new java.lang.String[] { "Seat", });
    internal_static_SeatUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SeatUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SeatUpdateRequest_descriptor,
        new java.lang.String[] { "Seat", "Id", });
    internal_static_SeatUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SeatUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SeatUpdateResponse_descriptor,
        new java.lang.String[] { "IsUpdated", });
    internal_static_MovieAmount_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_MovieAmount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieAmount_descriptor,
        new java.lang.String[] { "Id", "MovieName", "Amount", "ExpireDate", "MovieTime", });
    internal_static_MovieAmountGetAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_MovieAmountGetAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieAmountGetAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_MovieAmountGetAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_MovieAmountGetAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieAmountGetAllResponse_descriptor,
        new java.lang.String[] { "MovieAmount", });
    internal_static_MovieAmountUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_MovieAmountUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieAmountUpdateRequest_descriptor,
        new java.lang.String[] { "MovieAmount", "Id", });
    internal_static_MovieAmountUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_MovieAmountUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieAmountUpdateResponse_descriptor,
        new java.lang.String[] { "IsUpdated", });
    internal_static_MovieAmountInsertRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_MovieAmountInsertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieAmountInsertRequest_descriptor,
        new java.lang.String[] { "MovieAmount", });
    internal_static_MovieAmountInsertResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_MovieAmountInsertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieAmountInsertResponse_descriptor,
        new java.lang.String[] { "IsSaved", });
    internal_static_MovieAmountDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_MovieAmountDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieAmountDeleteRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_MovieAmountDeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_MovieAmountDeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovieAmountDeleteResponse_descriptor,
        new java.lang.String[] { "IsDelete", });
    internal_static_SalesMovie_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_SalesMovie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SalesMovie_descriptor,
        new java.lang.String[] { "Id", "MovieName", "CustomerName", "SeatCount", "TotalPrice", "IsCanceled", "SaleDate", });
    internal_static_SalesMovieGetAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_SalesMovieGetAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SalesMovieGetAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_SalesMovieGetAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_SalesMovieGetAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SalesMovieGetAllResponse_descriptor,
        new java.lang.String[] { "SalesMovie", });
    internal_static_SalesMovieInsertRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_SalesMovieInsertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SalesMovieInsertRequest_descriptor,
        new java.lang.String[] { "SalesMovie", });
    internal_static_SalesMovieInsertResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_SalesMovieInsertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SalesMovieInsertResponse_descriptor,
        new java.lang.String[] { "IsSaved", });
    internal_static_SalesMovieDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_SalesMovieDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SalesMovieDeleteRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_SalesMovieDeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_SalesMovieDeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SalesMovieDeleteResponse_descriptor,
        new java.lang.String[] { "IsDelete", });
    internal_static_SalesMovieCancelRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_SalesMovieCancelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SalesMovieCancelRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_SalesMovieCancelResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_SalesMovieCancelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SalesMovieCancelResponse_descriptor,
        new java.lang.String[] { "IsCanceled", });
    internal_static_CanceledSalesMovieGetAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_CanceledSalesMovieGetAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CanceledSalesMovieGetAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_CanceledSalesMovieGetAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_CanceledSalesMovieGetAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CanceledSalesMovieGetAllResponse_descriptor,
        new java.lang.String[] { "SalesMovie", });
    internal_static_ChangedAllCanceledSalesMovieGetAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_ChangedAllCanceledSalesMovieGetAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangedAllCanceledSalesMovieGetAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_ChangedAllCanceledSalesMovieGetAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_ChangedAllCanceledSalesMovieGetAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChangedAllCanceledSalesMovieGetAllResponse_descriptor,
        new java.lang.String[] { "IsCanceled", });
    internal_static_DeleteAllCanceledSalesMovieRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_DeleteAllCanceledSalesMovieRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteAllCanceledSalesMovieRequest_descriptor,
        new java.lang.String[] { });
    internal_static_DeleteAllChangeledSalesMovieResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_DeleteAllChangeledSalesMovieResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteAllChangeledSalesMovieResponse_descriptor,
        new java.lang.String[] { "IsDeletedAllChanged", });
    internal_static_CardInfo_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_CardInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CardInfo_descriptor,
        new java.lang.String[] { "Id", "CardOwnerName", "CardNumber", "Expiration", "Cvv", });
    internal_static_CardInfoGetAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_CardInfoGetAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CardInfoGetAllRequest_descriptor,
        new java.lang.String[] { });
    internal_static_CardInfoGetAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_CardInfoGetAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CardInfoGetAllResponse_descriptor,
        new java.lang.String[] { "CardInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
