// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface DeleteAllChangeledSalesMovieResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteAllChangeledSalesMovieResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isDeletedAllChanged = 1;</code>
   */
  boolean getIsDeletedAllChanged();
}
