// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface DeleteAllCanceledSalesMovieRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteAllCanceledSalesMovieRequest)
    com.google.protobuf.MessageOrBuilder {
}
