// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface MovieAmountInsertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MovieAmountInsertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MovieAmount movieAmount = 1;</code>
   */
  boolean hasMovieAmount();
  /**
   * <code>.MovieAmount movieAmount = 1;</code>
   */
  com.cinemaoperations.MovieAmount getMovieAmount();
  /**
   * <code>.MovieAmount movieAmount = 1;</code>
   */
  com.cinemaoperations.MovieAmountOrBuilder getMovieAmountOrBuilder();
}
