// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface MovieAmountInsertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MovieAmountInsertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isSaved = 1;</code>
   */
  boolean getIsSaved();
}
