// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface MovieAmountGetAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MovieAmountGetAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
