// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface MovieAmountUpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MovieAmountUpdateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isUpdated = 1;</code>
   */
  boolean getIsUpdated();
}
