// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface MovieAmountUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MovieAmountUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MovieAmount movieAmount = 1;</code>
   */
  boolean hasMovieAmount();
  /**
   * <code>.MovieAmount movieAmount = 1;</code>
   */
  com.cinemaoperations.MovieAmount getMovieAmount();
  /**
   * <code>.MovieAmount movieAmount = 1;</code>
   */
  com.cinemaoperations.MovieAmountOrBuilder getMovieAmountOrBuilder();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();
}
