// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

/**
 * Protobuf type {@code MovieAmountUpdateRequest}
 */
public  final class MovieAmountUpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MovieAmountUpdateRequest)
    MovieAmountUpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MovieAmountUpdateRequest.newBuilder() to construct.
  private MovieAmountUpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MovieAmountUpdateRequest() {
    id_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MovieAmountUpdateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.cinemaoperations.MovieAmount.Builder subBuilder = null;
            if (movieAmount_ != null) {
              subBuilder = movieAmount_.toBuilder();
            }
            movieAmount_ = input.readMessage(com.cinemaoperations.MovieAmount.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(movieAmount_);
              movieAmount_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            id_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cinemaoperations.Cinema.internal_static_MovieAmountUpdateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cinemaoperations.Cinema.internal_static_MovieAmountUpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cinemaoperations.MovieAmountUpdateRequest.class, com.cinemaoperations.MovieAmountUpdateRequest.Builder.class);
  }

  public static final int MOVIEAMOUNT_FIELD_NUMBER = 1;
  private com.cinemaoperations.MovieAmount movieAmount_;
  /**
   * <code>.MovieAmount movieAmount = 1;</code>
   */
  public boolean hasMovieAmount() {
    return movieAmount_ != null;
  }
  /**
   * <code>.MovieAmount movieAmount = 1;</code>
   */
  public com.cinemaoperations.MovieAmount getMovieAmount() {
    return movieAmount_ == null ? com.cinemaoperations.MovieAmount.getDefaultInstance() : movieAmount_;
  }
  /**
   * <code>.MovieAmount movieAmount = 1;</code>
   */
  public com.cinemaoperations.MovieAmountOrBuilder getMovieAmountOrBuilder() {
    return getMovieAmount();
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int id_;
  /**
   * <code>int32 id = 2;</code>
   */
  public int getId() {
    return id_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (movieAmount_ != null) {
      output.writeMessage(1, getMovieAmount());
    }
    if (id_ != 0) {
      output.writeInt32(2, id_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (movieAmount_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMovieAmount());
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cinemaoperations.MovieAmountUpdateRequest)) {
      return super.equals(obj);
    }
    com.cinemaoperations.MovieAmountUpdateRequest other = (com.cinemaoperations.MovieAmountUpdateRequest) obj;

    boolean result = true;
    result = result && (hasMovieAmount() == other.hasMovieAmount());
    if (hasMovieAmount()) {
      result = result && getMovieAmount()
          .equals(other.getMovieAmount());
    }
    result = result && (getId()
        == other.getId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMovieAmount()) {
      hash = (37 * hash) + MOVIEAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getMovieAmount().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cinemaoperations.MovieAmountUpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.MovieAmountUpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.MovieAmountUpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.MovieAmountUpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.MovieAmountUpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.MovieAmountUpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.MovieAmountUpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.MovieAmountUpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.MovieAmountUpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.MovieAmountUpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.MovieAmountUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.MovieAmountUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cinemaoperations.MovieAmountUpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MovieAmountUpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MovieAmountUpdateRequest)
      com.cinemaoperations.MovieAmountUpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cinemaoperations.Cinema.internal_static_MovieAmountUpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cinemaoperations.Cinema.internal_static_MovieAmountUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cinemaoperations.MovieAmountUpdateRequest.class, com.cinemaoperations.MovieAmountUpdateRequest.Builder.class);
    }

    // Construct using com.cinemaoperations.MovieAmountUpdateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (movieAmountBuilder_ == null) {
        movieAmount_ = null;
      } else {
        movieAmount_ = null;
        movieAmountBuilder_ = null;
      }
      id_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cinemaoperations.Cinema.internal_static_MovieAmountUpdateRequest_descriptor;
    }

    @java.lang.Override
    public com.cinemaoperations.MovieAmountUpdateRequest getDefaultInstanceForType() {
      return com.cinemaoperations.MovieAmountUpdateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.cinemaoperations.MovieAmountUpdateRequest build() {
      com.cinemaoperations.MovieAmountUpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cinemaoperations.MovieAmountUpdateRequest buildPartial() {
      com.cinemaoperations.MovieAmountUpdateRequest result = new com.cinemaoperations.MovieAmountUpdateRequest(this);
      if (movieAmountBuilder_ == null) {
        result.movieAmount_ = movieAmount_;
      } else {
        result.movieAmount_ = movieAmountBuilder_.build();
      }
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cinemaoperations.MovieAmountUpdateRequest) {
        return mergeFrom((com.cinemaoperations.MovieAmountUpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cinemaoperations.MovieAmountUpdateRequest other) {
      if (other == com.cinemaoperations.MovieAmountUpdateRequest.getDefaultInstance()) return this;
      if (other.hasMovieAmount()) {
        mergeMovieAmount(other.getMovieAmount());
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cinemaoperations.MovieAmountUpdateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cinemaoperations.MovieAmountUpdateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.cinemaoperations.MovieAmount movieAmount_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cinemaoperations.MovieAmount, com.cinemaoperations.MovieAmount.Builder, com.cinemaoperations.MovieAmountOrBuilder> movieAmountBuilder_;
    /**
     * <code>.MovieAmount movieAmount = 1;</code>
     */
    public boolean hasMovieAmount() {
      return movieAmountBuilder_ != null || movieAmount_ != null;
    }
    /**
     * <code>.MovieAmount movieAmount = 1;</code>
     */
    public com.cinemaoperations.MovieAmount getMovieAmount() {
      if (movieAmountBuilder_ == null) {
        return movieAmount_ == null ? com.cinemaoperations.MovieAmount.getDefaultInstance() : movieAmount_;
      } else {
        return movieAmountBuilder_.getMessage();
      }
    }
    /**
     * <code>.MovieAmount movieAmount = 1;</code>
     */
    public Builder setMovieAmount(com.cinemaoperations.MovieAmount value) {
      if (movieAmountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        movieAmount_ = value;
        onChanged();
      } else {
        movieAmountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.MovieAmount movieAmount = 1;</code>
     */
    public Builder setMovieAmount(
        com.cinemaoperations.MovieAmount.Builder builderForValue) {
      if (movieAmountBuilder_ == null) {
        movieAmount_ = builderForValue.build();
        onChanged();
      } else {
        movieAmountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.MovieAmount movieAmount = 1;</code>
     */
    public Builder mergeMovieAmount(com.cinemaoperations.MovieAmount value) {
      if (movieAmountBuilder_ == null) {
        if (movieAmount_ != null) {
          movieAmount_ =
            com.cinemaoperations.MovieAmount.newBuilder(movieAmount_).mergeFrom(value).buildPartial();
        } else {
          movieAmount_ = value;
        }
        onChanged();
      } else {
        movieAmountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.MovieAmount movieAmount = 1;</code>
     */
    public Builder clearMovieAmount() {
      if (movieAmountBuilder_ == null) {
        movieAmount_ = null;
        onChanged();
      } else {
        movieAmount_ = null;
        movieAmountBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.MovieAmount movieAmount = 1;</code>
     */
    public com.cinemaoperations.MovieAmount.Builder getMovieAmountBuilder() {
      
      onChanged();
      return getMovieAmountFieldBuilder().getBuilder();
    }
    /**
     * <code>.MovieAmount movieAmount = 1;</code>
     */
    public com.cinemaoperations.MovieAmountOrBuilder getMovieAmountOrBuilder() {
      if (movieAmountBuilder_ != null) {
        return movieAmountBuilder_.getMessageOrBuilder();
      } else {
        return movieAmount_ == null ?
            com.cinemaoperations.MovieAmount.getDefaultInstance() : movieAmount_;
      }
    }
    /**
     * <code>.MovieAmount movieAmount = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cinemaoperations.MovieAmount, com.cinemaoperations.MovieAmount.Builder, com.cinemaoperations.MovieAmountOrBuilder> 
        getMovieAmountFieldBuilder() {
      if (movieAmountBuilder_ == null) {
        movieAmountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cinemaoperations.MovieAmount, com.cinemaoperations.MovieAmount.Builder, com.cinemaoperations.MovieAmountOrBuilder>(
                getMovieAmount(),
                getParentForChildren(),
                isClean());
        movieAmount_ = null;
      }
      return movieAmountBuilder_;
    }

    private int id_ ;
    /**
     * <code>int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 2;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 2;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MovieAmountUpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:MovieAmountUpdateRequest)
  private static final com.cinemaoperations.MovieAmountUpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cinemaoperations.MovieAmountUpdateRequest();
  }

  public static com.cinemaoperations.MovieAmountUpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MovieAmountUpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<MovieAmountUpdateRequest>() {
    @java.lang.Override
    public MovieAmountUpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MovieAmountUpdateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MovieAmountUpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MovieAmountUpdateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cinemaoperations.MovieAmountUpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

