// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface MovieAmountGetAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MovieAmountGetAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MovieAmount movieAmount = 1;</code>
   */
  java.util.List<com.cinemaoperations.MovieAmount> 
      getMovieAmountList();
  /**
   * <code>repeated .MovieAmount movieAmount = 1;</code>
   */
  com.cinemaoperations.MovieAmount getMovieAmount(int index);
  /**
   * <code>repeated .MovieAmount movieAmount = 1;</code>
   */
  int getMovieAmountCount();
  /**
   * <code>repeated .MovieAmount movieAmount = 1;</code>
   */
  java.util.List<? extends com.cinemaoperations.MovieAmountOrBuilder> 
      getMovieAmountOrBuilderList();
  /**
   * <code>repeated .MovieAmount movieAmount = 1;</code>
   */
  com.cinemaoperations.MovieAmountOrBuilder getMovieAmountOrBuilder(
      int index);
}
