// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

/**
 * Protobuf type {@code MovieAmountGetAllResponse}
 */
public  final class MovieAmountGetAllResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MovieAmountGetAllResponse)
    MovieAmountGetAllResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MovieAmountGetAllResponse.newBuilder() to construct.
  private MovieAmountGetAllResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MovieAmountGetAllResponse() {
    movieAmount_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MovieAmountGetAllResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              movieAmount_ = new java.util.ArrayList<com.cinemaoperations.MovieAmount>();
              mutable_bitField0_ |= 0x00000001;
            }
            movieAmount_.add(
                input.readMessage(com.cinemaoperations.MovieAmount.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        movieAmount_ = java.util.Collections.unmodifiableList(movieAmount_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cinemaoperations.Cinema.internal_static_MovieAmountGetAllResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cinemaoperations.Cinema.internal_static_MovieAmountGetAllResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cinemaoperations.MovieAmountGetAllResponse.class, com.cinemaoperations.MovieAmountGetAllResponse.Builder.class);
  }

  public static final int MOVIEAMOUNT_FIELD_NUMBER = 1;
  private java.util.List<com.cinemaoperations.MovieAmount> movieAmount_;
  /**
   * <code>repeated .MovieAmount movieAmount = 1;</code>
   */
  public java.util.List<com.cinemaoperations.MovieAmount> getMovieAmountList() {
    return movieAmount_;
  }
  /**
   * <code>repeated .MovieAmount movieAmount = 1;</code>
   */
  public java.util.List<? extends com.cinemaoperations.MovieAmountOrBuilder> 
      getMovieAmountOrBuilderList() {
    return movieAmount_;
  }
  /**
   * <code>repeated .MovieAmount movieAmount = 1;</code>
   */
  public int getMovieAmountCount() {
    return movieAmount_.size();
  }
  /**
   * <code>repeated .MovieAmount movieAmount = 1;</code>
   */
  public com.cinemaoperations.MovieAmount getMovieAmount(int index) {
    return movieAmount_.get(index);
  }
  /**
   * <code>repeated .MovieAmount movieAmount = 1;</code>
   */
  public com.cinemaoperations.MovieAmountOrBuilder getMovieAmountOrBuilder(
      int index) {
    return movieAmount_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < movieAmount_.size(); i++) {
      output.writeMessage(1, movieAmount_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < movieAmount_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, movieAmount_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cinemaoperations.MovieAmountGetAllResponse)) {
      return super.equals(obj);
    }
    com.cinemaoperations.MovieAmountGetAllResponse other = (com.cinemaoperations.MovieAmountGetAllResponse) obj;

    boolean result = true;
    result = result && getMovieAmountList()
        .equals(other.getMovieAmountList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMovieAmountCount() > 0) {
      hash = (37 * hash) + MOVIEAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getMovieAmountList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cinemaoperations.MovieAmountGetAllResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.MovieAmountGetAllResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.MovieAmountGetAllResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.MovieAmountGetAllResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.MovieAmountGetAllResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.MovieAmountGetAllResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.MovieAmountGetAllResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.MovieAmountGetAllResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.MovieAmountGetAllResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.MovieAmountGetAllResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.MovieAmountGetAllResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.MovieAmountGetAllResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cinemaoperations.MovieAmountGetAllResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MovieAmountGetAllResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MovieAmountGetAllResponse)
      com.cinemaoperations.MovieAmountGetAllResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cinemaoperations.Cinema.internal_static_MovieAmountGetAllResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cinemaoperations.Cinema.internal_static_MovieAmountGetAllResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cinemaoperations.MovieAmountGetAllResponse.class, com.cinemaoperations.MovieAmountGetAllResponse.Builder.class);
    }

    // Construct using com.cinemaoperations.MovieAmountGetAllResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMovieAmountFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (movieAmountBuilder_ == null) {
        movieAmount_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        movieAmountBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cinemaoperations.Cinema.internal_static_MovieAmountGetAllResponse_descriptor;
    }

    @java.lang.Override
    public com.cinemaoperations.MovieAmountGetAllResponse getDefaultInstanceForType() {
      return com.cinemaoperations.MovieAmountGetAllResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.cinemaoperations.MovieAmountGetAllResponse build() {
      com.cinemaoperations.MovieAmountGetAllResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cinemaoperations.MovieAmountGetAllResponse buildPartial() {
      com.cinemaoperations.MovieAmountGetAllResponse result = new com.cinemaoperations.MovieAmountGetAllResponse(this);
      int from_bitField0_ = bitField0_;
      if (movieAmountBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          movieAmount_ = java.util.Collections.unmodifiableList(movieAmount_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.movieAmount_ = movieAmount_;
      } else {
        result.movieAmount_ = movieAmountBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cinemaoperations.MovieAmountGetAllResponse) {
        return mergeFrom((com.cinemaoperations.MovieAmountGetAllResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cinemaoperations.MovieAmountGetAllResponse other) {
      if (other == com.cinemaoperations.MovieAmountGetAllResponse.getDefaultInstance()) return this;
      if (movieAmountBuilder_ == null) {
        if (!other.movieAmount_.isEmpty()) {
          if (movieAmount_.isEmpty()) {
            movieAmount_ = other.movieAmount_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMovieAmountIsMutable();
            movieAmount_.addAll(other.movieAmount_);
          }
          onChanged();
        }
      } else {
        if (!other.movieAmount_.isEmpty()) {
          if (movieAmountBuilder_.isEmpty()) {
            movieAmountBuilder_.dispose();
            movieAmountBuilder_ = null;
            movieAmount_ = other.movieAmount_;
            bitField0_ = (bitField0_ & ~0x00000001);
            movieAmountBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMovieAmountFieldBuilder() : null;
          } else {
            movieAmountBuilder_.addAllMessages(other.movieAmount_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cinemaoperations.MovieAmountGetAllResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cinemaoperations.MovieAmountGetAllResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.cinemaoperations.MovieAmount> movieAmount_ =
      java.util.Collections.emptyList();
    private void ensureMovieAmountIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        movieAmount_ = new java.util.ArrayList<com.cinemaoperations.MovieAmount>(movieAmount_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cinemaoperations.MovieAmount, com.cinemaoperations.MovieAmount.Builder, com.cinemaoperations.MovieAmountOrBuilder> movieAmountBuilder_;

    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public java.util.List<com.cinemaoperations.MovieAmount> getMovieAmountList() {
      if (movieAmountBuilder_ == null) {
        return java.util.Collections.unmodifiableList(movieAmount_);
      } else {
        return movieAmountBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public int getMovieAmountCount() {
      if (movieAmountBuilder_ == null) {
        return movieAmount_.size();
      } else {
        return movieAmountBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public com.cinemaoperations.MovieAmount getMovieAmount(int index) {
      if (movieAmountBuilder_ == null) {
        return movieAmount_.get(index);
      } else {
        return movieAmountBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public Builder setMovieAmount(
        int index, com.cinemaoperations.MovieAmount value) {
      if (movieAmountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMovieAmountIsMutable();
        movieAmount_.set(index, value);
        onChanged();
      } else {
        movieAmountBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public Builder setMovieAmount(
        int index, com.cinemaoperations.MovieAmount.Builder builderForValue) {
      if (movieAmountBuilder_ == null) {
        ensureMovieAmountIsMutable();
        movieAmount_.set(index, builderForValue.build());
        onChanged();
      } else {
        movieAmountBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public Builder addMovieAmount(com.cinemaoperations.MovieAmount value) {
      if (movieAmountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMovieAmountIsMutable();
        movieAmount_.add(value);
        onChanged();
      } else {
        movieAmountBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public Builder addMovieAmount(
        int index, com.cinemaoperations.MovieAmount value) {
      if (movieAmountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMovieAmountIsMutable();
        movieAmount_.add(index, value);
        onChanged();
      } else {
        movieAmountBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public Builder addMovieAmount(
        com.cinemaoperations.MovieAmount.Builder builderForValue) {
      if (movieAmountBuilder_ == null) {
        ensureMovieAmountIsMutable();
        movieAmount_.add(builderForValue.build());
        onChanged();
      } else {
        movieAmountBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public Builder addMovieAmount(
        int index, com.cinemaoperations.MovieAmount.Builder builderForValue) {
      if (movieAmountBuilder_ == null) {
        ensureMovieAmountIsMutable();
        movieAmount_.add(index, builderForValue.build());
        onChanged();
      } else {
        movieAmountBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public Builder addAllMovieAmount(
        java.lang.Iterable<? extends com.cinemaoperations.MovieAmount> values) {
      if (movieAmountBuilder_ == null) {
        ensureMovieAmountIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, movieAmount_);
        onChanged();
      } else {
        movieAmountBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public Builder clearMovieAmount() {
      if (movieAmountBuilder_ == null) {
        movieAmount_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        movieAmountBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public Builder removeMovieAmount(int index) {
      if (movieAmountBuilder_ == null) {
        ensureMovieAmountIsMutable();
        movieAmount_.remove(index);
        onChanged();
      } else {
        movieAmountBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public com.cinemaoperations.MovieAmount.Builder getMovieAmountBuilder(
        int index) {
      return getMovieAmountFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public com.cinemaoperations.MovieAmountOrBuilder getMovieAmountOrBuilder(
        int index) {
      if (movieAmountBuilder_ == null) {
        return movieAmount_.get(index);  } else {
        return movieAmountBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public java.util.List<? extends com.cinemaoperations.MovieAmountOrBuilder> 
         getMovieAmountOrBuilderList() {
      if (movieAmountBuilder_ != null) {
        return movieAmountBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(movieAmount_);
      }
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public com.cinemaoperations.MovieAmount.Builder addMovieAmountBuilder() {
      return getMovieAmountFieldBuilder().addBuilder(
          com.cinemaoperations.MovieAmount.getDefaultInstance());
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public com.cinemaoperations.MovieAmount.Builder addMovieAmountBuilder(
        int index) {
      return getMovieAmountFieldBuilder().addBuilder(
          index, com.cinemaoperations.MovieAmount.getDefaultInstance());
    }
    /**
     * <code>repeated .MovieAmount movieAmount = 1;</code>
     */
    public java.util.List<com.cinemaoperations.MovieAmount.Builder> 
         getMovieAmountBuilderList() {
      return getMovieAmountFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cinemaoperations.MovieAmount, com.cinemaoperations.MovieAmount.Builder, com.cinemaoperations.MovieAmountOrBuilder> 
        getMovieAmountFieldBuilder() {
      if (movieAmountBuilder_ == null) {
        movieAmountBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.cinemaoperations.MovieAmount, com.cinemaoperations.MovieAmount.Builder, com.cinemaoperations.MovieAmountOrBuilder>(
                movieAmount_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        movieAmount_ = null;
      }
      return movieAmountBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MovieAmountGetAllResponse)
  }

  // @@protoc_insertion_point(class_scope:MovieAmountGetAllResponse)
  private static final com.cinemaoperations.MovieAmountGetAllResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cinemaoperations.MovieAmountGetAllResponse();
  }

  public static com.cinemaoperations.MovieAmountGetAllResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MovieAmountGetAllResponse>
      PARSER = new com.google.protobuf.AbstractParser<MovieAmountGetAllResponse>() {
    @java.lang.Override
    public MovieAmountGetAllResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MovieAmountGetAllResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MovieAmountGetAllResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MovieAmountGetAllResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cinemaoperations.MovieAmountGetAllResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

