// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface MovieAmountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MovieAmount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string movie_name = 2;</code>
   */
  java.lang.String getMovieName();
  /**
   * <code>string movie_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getMovieNameBytes();

  /**
   * <code>int64 amount = 3;</code>
   */
  long getAmount();

  /**
   * <code>string expire_date = 4;</code>
   */
  java.lang.String getExpireDate();
  /**
   * <code>string expire_date = 4;</code>
   */
  com.google.protobuf.ByteString
      getExpireDateBytes();

  /**
   * <code>int64 movie_time = 5;</code>
   */
  long getMovieTime();
}
