// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface SalesMovieInsertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SalesMovieInsertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SalesMovie salesMovie = 1;</code>
   */
  boolean hasSalesMovie();
  /**
   * <code>.SalesMovie salesMovie = 1;</code>
   */
  com.cinemaoperations.SalesMovie getSalesMovie();
  /**
   * <code>.SalesMovie salesMovie = 1;</code>
   */
  com.cinemaoperations.SalesMovieOrBuilder getSalesMovieOrBuilder();
}
