// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

/**
 * Protobuf type {@code SalesMovie}
 */
public  final class SalesMovie extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SalesMovie)
    SalesMovieOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SalesMovie.newBuilder() to construct.
  private SalesMovie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SalesMovie() {
    id_ = 0L;
    movieName_ = "";
    customerName_ = "";
    seatCount_ = 0L;
    totalPrice_ = 0L;
    isCanceled_ = false;
    saleDate_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SalesMovie(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            movieName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            customerName_ = s;
            break;
          }
          case 32: {

            seatCount_ = input.readInt64();
            break;
          }
          case 40: {

            totalPrice_ = input.readInt64();
            break;
          }
          case 48: {

            isCanceled_ = input.readBool();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            saleDate_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cinemaoperations.Cinema.internal_static_SalesMovie_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cinemaoperations.Cinema.internal_static_SalesMovie_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cinemaoperations.SalesMovie.class, com.cinemaoperations.SalesMovie.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int MOVIE_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object movieName_;
  /**
   * <code>string movie_name = 2;</code>
   */
  public java.lang.String getMovieName() {
    java.lang.Object ref = movieName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      movieName_ = s;
      return s;
    }
  }
  /**
   * <code>string movie_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMovieNameBytes() {
    java.lang.Object ref = movieName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      movieName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMER_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object customerName_;
  /**
   * <code>string customer_name = 3;</code>
   */
  public java.lang.String getCustomerName() {
    java.lang.Object ref = customerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      customerName_ = s;
      return s;
    }
  }
  /**
   * <code>string customer_name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCustomerNameBytes() {
    java.lang.Object ref = customerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEAT_COUNT_FIELD_NUMBER = 4;
  private long seatCount_;
  /**
   * <code>int64 seat_count = 4;</code>
   */
  public long getSeatCount() {
    return seatCount_;
  }

  public static final int TOTAL_PRICE_FIELD_NUMBER = 5;
  private long totalPrice_;
  /**
   * <code>int64 total_price = 5;</code>
   */
  public long getTotalPrice() {
    return totalPrice_;
  }

  public static final int IS_CANCELED_FIELD_NUMBER = 6;
  private boolean isCanceled_;
  /**
   * <code>bool is_canceled = 6;</code>
   */
  public boolean getIsCanceled() {
    return isCanceled_;
  }

  public static final int SALE_DATE_FIELD_NUMBER = 7;
  private volatile java.lang.Object saleDate_;
  /**
   * <code>string sale_date = 7;</code>
   */
  public java.lang.String getSaleDate() {
    java.lang.Object ref = saleDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      saleDate_ = s;
      return s;
    }
  }
  /**
   * <code>string sale_date = 7;</code>
   */
  public com.google.protobuf.ByteString
      getSaleDateBytes() {
    java.lang.Object ref = saleDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      saleDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getMovieNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, movieName_);
    }
    if (!getCustomerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, customerName_);
    }
    if (seatCount_ != 0L) {
      output.writeInt64(4, seatCount_);
    }
    if (totalPrice_ != 0L) {
      output.writeInt64(5, totalPrice_);
    }
    if (isCanceled_ != false) {
      output.writeBool(6, isCanceled_);
    }
    if (!getSaleDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, saleDate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getMovieNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, movieName_);
    }
    if (!getCustomerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, customerName_);
    }
    if (seatCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, seatCount_);
    }
    if (totalPrice_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, totalPrice_);
    }
    if (isCanceled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, isCanceled_);
    }
    if (!getSaleDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, saleDate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cinemaoperations.SalesMovie)) {
      return super.equals(obj);
    }
    com.cinemaoperations.SalesMovie other = (com.cinemaoperations.SalesMovie) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getMovieName()
        .equals(other.getMovieName());
    result = result && getCustomerName()
        .equals(other.getCustomerName());
    result = result && (getSeatCount()
        == other.getSeatCount());
    result = result && (getTotalPrice()
        == other.getTotalPrice());
    result = result && (getIsCanceled()
        == other.getIsCanceled());
    result = result && getSaleDate()
        .equals(other.getSaleDate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + MOVIE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getMovieName().hashCode();
    hash = (37 * hash) + CUSTOMER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerName().hashCode();
    hash = (37 * hash) + SEAT_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSeatCount());
    hash = (37 * hash) + TOTAL_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalPrice());
    hash = (37 * hash) + IS_CANCELED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsCanceled());
    hash = (37 * hash) + SALE_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getSaleDate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cinemaoperations.SalesMovie parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.SalesMovie parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.SalesMovie parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.SalesMovie parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.SalesMovie parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.SalesMovie parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.SalesMovie parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.SalesMovie parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.SalesMovie parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.SalesMovie parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.SalesMovie parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.SalesMovie parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cinemaoperations.SalesMovie prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SalesMovie}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SalesMovie)
      com.cinemaoperations.SalesMovieOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cinemaoperations.Cinema.internal_static_SalesMovie_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cinemaoperations.Cinema.internal_static_SalesMovie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cinemaoperations.SalesMovie.class, com.cinemaoperations.SalesMovie.Builder.class);
    }

    // Construct using com.cinemaoperations.SalesMovie.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      movieName_ = "";

      customerName_ = "";

      seatCount_ = 0L;

      totalPrice_ = 0L;

      isCanceled_ = false;

      saleDate_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cinemaoperations.Cinema.internal_static_SalesMovie_descriptor;
    }

    @java.lang.Override
    public com.cinemaoperations.SalesMovie getDefaultInstanceForType() {
      return com.cinemaoperations.SalesMovie.getDefaultInstance();
    }

    @java.lang.Override
    public com.cinemaoperations.SalesMovie build() {
      com.cinemaoperations.SalesMovie result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cinemaoperations.SalesMovie buildPartial() {
      com.cinemaoperations.SalesMovie result = new com.cinemaoperations.SalesMovie(this);
      result.id_ = id_;
      result.movieName_ = movieName_;
      result.customerName_ = customerName_;
      result.seatCount_ = seatCount_;
      result.totalPrice_ = totalPrice_;
      result.isCanceled_ = isCanceled_;
      result.saleDate_ = saleDate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cinemaoperations.SalesMovie) {
        return mergeFrom((com.cinemaoperations.SalesMovie)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cinemaoperations.SalesMovie other) {
      if (other == com.cinemaoperations.SalesMovie.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getMovieName().isEmpty()) {
        movieName_ = other.movieName_;
        onChanged();
      }
      if (!other.getCustomerName().isEmpty()) {
        customerName_ = other.customerName_;
        onChanged();
      }
      if (other.getSeatCount() != 0L) {
        setSeatCount(other.getSeatCount());
      }
      if (other.getTotalPrice() != 0L) {
        setTotalPrice(other.getTotalPrice());
      }
      if (other.getIsCanceled() != false) {
        setIsCanceled(other.getIsCanceled());
      }
      if (!other.getSaleDate().isEmpty()) {
        saleDate_ = other.saleDate_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cinemaoperations.SalesMovie parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cinemaoperations.SalesMovie) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object movieName_ = "";
    /**
     * <code>string movie_name = 2;</code>
     */
    public java.lang.String getMovieName() {
      java.lang.Object ref = movieName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        movieName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string movie_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMovieNameBytes() {
      java.lang.Object ref = movieName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        movieName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string movie_name = 2;</code>
     */
    public Builder setMovieName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      movieName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string movie_name = 2;</code>
     */
    public Builder clearMovieName() {
      
      movieName_ = getDefaultInstance().getMovieName();
      onChanged();
      return this;
    }
    /**
     * <code>string movie_name = 2;</code>
     */
    public Builder setMovieNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      movieName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object customerName_ = "";
    /**
     * <code>string customer_name = 3;</code>
     */
    public java.lang.String getCustomerName() {
      java.lang.Object ref = customerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string customer_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCustomerNameBytes() {
      java.lang.Object ref = customerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customer_name = 3;</code>
     */
    public Builder setCustomerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string customer_name = 3;</code>
     */
    public Builder clearCustomerName() {
      
      customerName_ = getDefaultInstance().getCustomerName();
      onChanged();
      return this;
    }
    /**
     * <code>string customer_name = 3;</code>
     */
    public Builder setCustomerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customerName_ = value;
      onChanged();
      return this;
    }

    private long seatCount_ ;
    /**
     * <code>int64 seat_count = 4;</code>
     */
    public long getSeatCount() {
      return seatCount_;
    }
    /**
     * <code>int64 seat_count = 4;</code>
     */
    public Builder setSeatCount(long value) {
      
      seatCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 seat_count = 4;</code>
     */
    public Builder clearSeatCount() {
      
      seatCount_ = 0L;
      onChanged();
      return this;
    }

    private long totalPrice_ ;
    /**
     * <code>int64 total_price = 5;</code>
     */
    public long getTotalPrice() {
      return totalPrice_;
    }
    /**
     * <code>int64 total_price = 5;</code>
     */
    public Builder setTotalPrice(long value) {
      
      totalPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total_price = 5;</code>
     */
    public Builder clearTotalPrice() {
      
      totalPrice_ = 0L;
      onChanged();
      return this;
    }

    private boolean isCanceled_ ;
    /**
     * <code>bool is_canceled = 6;</code>
     */
    public boolean getIsCanceled() {
      return isCanceled_;
    }
    /**
     * <code>bool is_canceled = 6;</code>
     */
    public Builder setIsCanceled(boolean value) {
      
      isCanceled_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_canceled = 6;</code>
     */
    public Builder clearIsCanceled() {
      
      isCanceled_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object saleDate_ = "";
    /**
     * <code>string sale_date = 7;</code>
     */
    public java.lang.String getSaleDate() {
      java.lang.Object ref = saleDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        saleDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sale_date = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSaleDateBytes() {
      java.lang.Object ref = saleDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        saleDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sale_date = 7;</code>
     */
    public Builder setSaleDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      saleDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sale_date = 7;</code>
     */
    public Builder clearSaleDate() {
      
      saleDate_ = getDefaultInstance().getSaleDate();
      onChanged();
      return this;
    }
    /**
     * <code>string sale_date = 7;</code>
     */
    public Builder setSaleDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      saleDate_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SalesMovie)
  }

  // @@protoc_insertion_point(class_scope:SalesMovie)
  private static final com.cinemaoperations.SalesMovie DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cinemaoperations.SalesMovie();
  }

  public static com.cinemaoperations.SalesMovie getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SalesMovie>
      PARSER = new com.google.protobuf.AbstractParser<SalesMovie>() {
    @java.lang.Override
    public SalesMovie parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SalesMovie(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SalesMovie> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SalesMovie> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cinemaoperations.SalesMovie getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

