// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface SalesMovieGetAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SalesMovieGetAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
