// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

/**
 * Protobuf type {@code SalesMovieInsertRequest}
 */
public  final class SalesMovieInsertRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SalesMovieInsertRequest)
    SalesMovieInsertRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SalesMovieInsertRequest.newBuilder() to construct.
  private SalesMovieInsertRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SalesMovieInsertRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SalesMovieInsertRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.cinemaoperations.SalesMovie.Builder subBuilder = null;
            if (salesMovie_ != null) {
              subBuilder = salesMovie_.toBuilder();
            }
            salesMovie_ = input.readMessage(com.cinemaoperations.SalesMovie.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(salesMovie_);
              salesMovie_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cinemaoperations.Cinema.internal_static_SalesMovieInsertRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cinemaoperations.Cinema.internal_static_SalesMovieInsertRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cinemaoperations.SalesMovieInsertRequest.class, com.cinemaoperations.SalesMovieInsertRequest.Builder.class);
  }

  public static final int SALESMOVIE_FIELD_NUMBER = 1;
  private com.cinemaoperations.SalesMovie salesMovie_;
  /**
   * <code>.SalesMovie salesMovie = 1;</code>
   */
  public boolean hasSalesMovie() {
    return salesMovie_ != null;
  }
  /**
   * <code>.SalesMovie salesMovie = 1;</code>
   */
  public com.cinemaoperations.SalesMovie getSalesMovie() {
    return salesMovie_ == null ? com.cinemaoperations.SalesMovie.getDefaultInstance() : salesMovie_;
  }
  /**
   * <code>.SalesMovie salesMovie = 1;</code>
   */
  public com.cinemaoperations.SalesMovieOrBuilder getSalesMovieOrBuilder() {
    return getSalesMovie();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (salesMovie_ != null) {
      output.writeMessage(1, getSalesMovie());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (salesMovie_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSalesMovie());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cinemaoperations.SalesMovieInsertRequest)) {
      return super.equals(obj);
    }
    com.cinemaoperations.SalesMovieInsertRequest other = (com.cinemaoperations.SalesMovieInsertRequest) obj;

    boolean result = true;
    result = result && (hasSalesMovie() == other.hasSalesMovie());
    if (hasSalesMovie()) {
      result = result && getSalesMovie()
          .equals(other.getSalesMovie());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSalesMovie()) {
      hash = (37 * hash) + SALESMOVIE_FIELD_NUMBER;
      hash = (53 * hash) + getSalesMovie().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cinemaoperations.SalesMovieInsertRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.SalesMovieInsertRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.SalesMovieInsertRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.SalesMovieInsertRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.SalesMovieInsertRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.SalesMovieInsertRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.SalesMovieInsertRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.SalesMovieInsertRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.SalesMovieInsertRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.SalesMovieInsertRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.SalesMovieInsertRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.SalesMovieInsertRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cinemaoperations.SalesMovieInsertRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SalesMovieInsertRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SalesMovieInsertRequest)
      com.cinemaoperations.SalesMovieInsertRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cinemaoperations.Cinema.internal_static_SalesMovieInsertRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cinemaoperations.Cinema.internal_static_SalesMovieInsertRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cinemaoperations.SalesMovieInsertRequest.class, com.cinemaoperations.SalesMovieInsertRequest.Builder.class);
    }

    // Construct using com.cinemaoperations.SalesMovieInsertRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (salesMovieBuilder_ == null) {
        salesMovie_ = null;
      } else {
        salesMovie_ = null;
        salesMovieBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cinemaoperations.Cinema.internal_static_SalesMovieInsertRequest_descriptor;
    }

    @java.lang.Override
    public com.cinemaoperations.SalesMovieInsertRequest getDefaultInstanceForType() {
      return com.cinemaoperations.SalesMovieInsertRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.cinemaoperations.SalesMovieInsertRequest build() {
      com.cinemaoperations.SalesMovieInsertRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cinemaoperations.SalesMovieInsertRequest buildPartial() {
      com.cinemaoperations.SalesMovieInsertRequest result = new com.cinemaoperations.SalesMovieInsertRequest(this);
      if (salesMovieBuilder_ == null) {
        result.salesMovie_ = salesMovie_;
      } else {
        result.salesMovie_ = salesMovieBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cinemaoperations.SalesMovieInsertRequest) {
        return mergeFrom((com.cinemaoperations.SalesMovieInsertRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cinemaoperations.SalesMovieInsertRequest other) {
      if (other == com.cinemaoperations.SalesMovieInsertRequest.getDefaultInstance()) return this;
      if (other.hasSalesMovie()) {
        mergeSalesMovie(other.getSalesMovie());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cinemaoperations.SalesMovieInsertRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cinemaoperations.SalesMovieInsertRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.cinemaoperations.SalesMovie salesMovie_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cinemaoperations.SalesMovie, com.cinemaoperations.SalesMovie.Builder, com.cinemaoperations.SalesMovieOrBuilder> salesMovieBuilder_;
    /**
     * <code>.SalesMovie salesMovie = 1;</code>
     */
    public boolean hasSalesMovie() {
      return salesMovieBuilder_ != null || salesMovie_ != null;
    }
    /**
     * <code>.SalesMovie salesMovie = 1;</code>
     */
    public com.cinemaoperations.SalesMovie getSalesMovie() {
      if (salesMovieBuilder_ == null) {
        return salesMovie_ == null ? com.cinemaoperations.SalesMovie.getDefaultInstance() : salesMovie_;
      } else {
        return salesMovieBuilder_.getMessage();
      }
    }
    /**
     * <code>.SalesMovie salesMovie = 1;</code>
     */
    public Builder setSalesMovie(com.cinemaoperations.SalesMovie value) {
      if (salesMovieBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        salesMovie_ = value;
        onChanged();
      } else {
        salesMovieBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.SalesMovie salesMovie = 1;</code>
     */
    public Builder setSalesMovie(
        com.cinemaoperations.SalesMovie.Builder builderForValue) {
      if (salesMovieBuilder_ == null) {
        salesMovie_ = builderForValue.build();
        onChanged();
      } else {
        salesMovieBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.SalesMovie salesMovie = 1;</code>
     */
    public Builder mergeSalesMovie(com.cinemaoperations.SalesMovie value) {
      if (salesMovieBuilder_ == null) {
        if (salesMovie_ != null) {
          salesMovie_ =
            com.cinemaoperations.SalesMovie.newBuilder(salesMovie_).mergeFrom(value).buildPartial();
        } else {
          salesMovie_ = value;
        }
        onChanged();
      } else {
        salesMovieBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.SalesMovie salesMovie = 1;</code>
     */
    public Builder clearSalesMovie() {
      if (salesMovieBuilder_ == null) {
        salesMovie_ = null;
        onChanged();
      } else {
        salesMovie_ = null;
        salesMovieBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.SalesMovie salesMovie = 1;</code>
     */
    public com.cinemaoperations.SalesMovie.Builder getSalesMovieBuilder() {
      
      onChanged();
      return getSalesMovieFieldBuilder().getBuilder();
    }
    /**
     * <code>.SalesMovie salesMovie = 1;</code>
     */
    public com.cinemaoperations.SalesMovieOrBuilder getSalesMovieOrBuilder() {
      if (salesMovieBuilder_ != null) {
        return salesMovieBuilder_.getMessageOrBuilder();
      } else {
        return salesMovie_ == null ?
            com.cinemaoperations.SalesMovie.getDefaultInstance() : salesMovie_;
      }
    }
    /**
     * <code>.SalesMovie salesMovie = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cinemaoperations.SalesMovie, com.cinemaoperations.SalesMovie.Builder, com.cinemaoperations.SalesMovieOrBuilder> 
        getSalesMovieFieldBuilder() {
      if (salesMovieBuilder_ == null) {
        salesMovieBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cinemaoperations.SalesMovie, com.cinemaoperations.SalesMovie.Builder, com.cinemaoperations.SalesMovieOrBuilder>(
                getSalesMovie(),
                getParentForChildren(),
                isClean());
        salesMovie_ = null;
      }
      return salesMovieBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SalesMovieInsertRequest)
  }

  // @@protoc_insertion_point(class_scope:SalesMovieInsertRequest)
  private static final com.cinemaoperations.SalesMovieInsertRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cinemaoperations.SalesMovieInsertRequest();
  }

  public static com.cinemaoperations.SalesMovieInsertRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SalesMovieInsertRequest>
      PARSER = new com.google.protobuf.AbstractParser<SalesMovieInsertRequest>() {
    @java.lang.Override
    public SalesMovieInsertRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SalesMovieInsertRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SalesMovieInsertRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SalesMovieInsertRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cinemaoperations.SalesMovieInsertRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

