// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface SalesMovieOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SalesMovie)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string movie_name = 2;</code>
   */
  java.lang.String getMovieName();
  /**
   * <code>string movie_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getMovieNameBytes();

  /**
   * <code>string customer_name = 3;</code>
   */
  java.lang.String getCustomerName();
  /**
   * <code>string customer_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();

  /**
   * <code>int64 seat_count = 4;</code>
   */
  long getSeatCount();

  /**
   * <code>int64 total_price = 5;</code>
   */
  long getTotalPrice();

  /**
   * <code>bool is_canceled = 6;</code>
   */
  boolean getIsCanceled();

  /**
   * <code>string sale_date = 7;</code>
   */
  java.lang.String getSaleDate();
  /**
   * <code>string sale_date = 7;</code>
   */
  com.google.protobuf.ByteString
      getSaleDateBytes();
}
