// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface SalesMovieDeleteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SalesMovieDeleteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isDelete = 1;</code>
   */
  boolean getIsDelete();
}
