// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface SalesMovieDeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SalesMovieDeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
