// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface SeatGetAllRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SeatGetAllRequest)
    com.google.protobuf.MessageOrBuilder {
}
