// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface SeatGetAllResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SeatGetAllResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Seat seat = 1;</code>
   */
  java.util.List<com.cinemaoperations.Seat> 
      getSeatList();
  /**
   * <code>repeated .Seat seat = 1;</code>
   */
  com.cinemaoperations.Seat getSeat(int index);
  /**
   * <code>repeated .Seat seat = 1;</code>
   */
  int getSeatCount();
  /**
   * <code>repeated .Seat seat = 1;</code>
   */
  java.util.List<? extends com.cinemaoperations.SeatOrBuilder> 
      getSeatOrBuilderList();
  /**
   * <code>repeated .Seat seat = 1;</code>
   */
  com.cinemaoperations.SeatOrBuilder getSeatOrBuilder(
      int index);
}
