// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface SeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Seat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>bool seat_status = 2;</code>
   */
  boolean getSeatStatus();
}
