// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

public interface SeatUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SeatUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Seat seat = 1;</code>
   */
  boolean hasSeat();
  /**
   * <code>.Seat seat = 1;</code>
   */
  com.cinemaoperations.Seat getSeat();
  /**
   * <code>.Seat seat = 1;</code>
   */
  com.cinemaoperations.SeatOrBuilder getSeatOrBuilder();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();
}
