// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cinema.proto

package com.cinemaoperations;

/**
 * Protobuf type {@code SeatUpdateRequest}
 */
public  final class SeatUpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SeatUpdateRequest)
    SeatUpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SeatUpdateRequest.newBuilder() to construct.
  private SeatUpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SeatUpdateRequest() {
    id_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SeatUpdateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.cinemaoperations.Seat.Builder subBuilder = null;
            if (seat_ != null) {
              subBuilder = seat_.toBuilder();
            }
            seat_ = input.readMessage(com.cinemaoperations.Seat.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(seat_);
              seat_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            id_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cinemaoperations.Cinema.internal_static_SeatUpdateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cinemaoperations.Cinema.internal_static_SeatUpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cinemaoperations.SeatUpdateRequest.class, com.cinemaoperations.SeatUpdateRequest.Builder.class);
  }

  public static final int SEAT_FIELD_NUMBER = 1;
  private com.cinemaoperations.Seat seat_;
  /**
   * <code>.Seat seat = 1;</code>
   */
  public boolean hasSeat() {
    return seat_ != null;
  }
  /**
   * <code>.Seat seat = 1;</code>
   */
  public com.cinemaoperations.Seat getSeat() {
    return seat_ == null ? com.cinemaoperations.Seat.getDefaultInstance() : seat_;
  }
  /**
   * <code>.Seat seat = 1;</code>
   */
  public com.cinemaoperations.SeatOrBuilder getSeatOrBuilder() {
    return getSeat();
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int id_;
  /**
   * <code>int32 id = 2;</code>
   */
  public int getId() {
    return id_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (seat_ != null) {
      output.writeMessage(1, getSeat());
    }
    if (id_ != 0) {
      output.writeInt32(2, id_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (seat_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSeat());
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cinemaoperations.SeatUpdateRequest)) {
      return super.equals(obj);
    }
    com.cinemaoperations.SeatUpdateRequest other = (com.cinemaoperations.SeatUpdateRequest) obj;

    boolean result = true;
    result = result && (hasSeat() == other.hasSeat());
    if (hasSeat()) {
      result = result && getSeat()
          .equals(other.getSeat());
    }
    result = result && (getId()
        == other.getId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSeat()) {
      hash = (37 * hash) + SEAT_FIELD_NUMBER;
      hash = (53 * hash) + getSeat().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cinemaoperations.SeatUpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.SeatUpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.SeatUpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.SeatUpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.SeatUpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cinemaoperations.SeatUpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cinemaoperations.SeatUpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.SeatUpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.SeatUpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.SeatUpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cinemaoperations.SeatUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cinemaoperations.SeatUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cinemaoperations.SeatUpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SeatUpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SeatUpdateRequest)
      com.cinemaoperations.SeatUpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cinemaoperations.Cinema.internal_static_SeatUpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cinemaoperations.Cinema.internal_static_SeatUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cinemaoperations.SeatUpdateRequest.class, com.cinemaoperations.SeatUpdateRequest.Builder.class);
    }

    // Construct using com.cinemaoperations.SeatUpdateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (seatBuilder_ == null) {
        seat_ = null;
      } else {
        seat_ = null;
        seatBuilder_ = null;
      }
      id_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cinemaoperations.Cinema.internal_static_SeatUpdateRequest_descriptor;
    }

    @java.lang.Override
    public com.cinemaoperations.SeatUpdateRequest getDefaultInstanceForType() {
      return com.cinemaoperations.SeatUpdateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.cinemaoperations.SeatUpdateRequest build() {
      com.cinemaoperations.SeatUpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cinemaoperations.SeatUpdateRequest buildPartial() {
      com.cinemaoperations.SeatUpdateRequest result = new com.cinemaoperations.SeatUpdateRequest(this);
      if (seatBuilder_ == null) {
        result.seat_ = seat_;
      } else {
        result.seat_ = seatBuilder_.build();
      }
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cinemaoperations.SeatUpdateRequest) {
        return mergeFrom((com.cinemaoperations.SeatUpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cinemaoperations.SeatUpdateRequest other) {
      if (other == com.cinemaoperations.SeatUpdateRequest.getDefaultInstance()) return this;
      if (other.hasSeat()) {
        mergeSeat(other.getSeat());
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cinemaoperations.SeatUpdateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cinemaoperations.SeatUpdateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.cinemaoperations.Seat seat_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cinemaoperations.Seat, com.cinemaoperations.Seat.Builder, com.cinemaoperations.SeatOrBuilder> seatBuilder_;
    /**
     * <code>.Seat seat = 1;</code>
     */
    public boolean hasSeat() {
      return seatBuilder_ != null || seat_ != null;
    }
    /**
     * <code>.Seat seat = 1;</code>
     */
    public com.cinemaoperations.Seat getSeat() {
      if (seatBuilder_ == null) {
        return seat_ == null ? com.cinemaoperations.Seat.getDefaultInstance() : seat_;
      } else {
        return seatBuilder_.getMessage();
      }
    }
    /**
     * <code>.Seat seat = 1;</code>
     */
    public Builder setSeat(com.cinemaoperations.Seat value) {
      if (seatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        seat_ = value;
        onChanged();
      } else {
        seatBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Seat seat = 1;</code>
     */
    public Builder setSeat(
        com.cinemaoperations.Seat.Builder builderForValue) {
      if (seatBuilder_ == null) {
        seat_ = builderForValue.build();
        onChanged();
      } else {
        seatBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Seat seat = 1;</code>
     */
    public Builder mergeSeat(com.cinemaoperations.Seat value) {
      if (seatBuilder_ == null) {
        if (seat_ != null) {
          seat_ =
            com.cinemaoperations.Seat.newBuilder(seat_).mergeFrom(value).buildPartial();
        } else {
          seat_ = value;
        }
        onChanged();
      } else {
        seatBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Seat seat = 1;</code>
     */
    public Builder clearSeat() {
      if (seatBuilder_ == null) {
        seat_ = null;
        onChanged();
      } else {
        seat_ = null;
        seatBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Seat seat = 1;</code>
     */
    public com.cinemaoperations.Seat.Builder getSeatBuilder() {
      
      onChanged();
      return getSeatFieldBuilder().getBuilder();
    }
    /**
     * <code>.Seat seat = 1;</code>
     */
    public com.cinemaoperations.SeatOrBuilder getSeatOrBuilder() {
      if (seatBuilder_ != null) {
        return seatBuilder_.getMessageOrBuilder();
      } else {
        return seat_ == null ?
            com.cinemaoperations.Seat.getDefaultInstance() : seat_;
      }
    }
    /**
     * <code>.Seat seat = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.cinemaoperations.Seat, com.cinemaoperations.Seat.Builder, com.cinemaoperations.SeatOrBuilder> 
        getSeatFieldBuilder() {
      if (seatBuilder_ == null) {
        seatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.cinemaoperations.Seat, com.cinemaoperations.Seat.Builder, com.cinemaoperations.SeatOrBuilder>(
                getSeat(),
                getParentForChildren(),
                isClean());
        seat_ = null;
      }
      return seatBuilder_;
    }

    private int id_ ;
    /**
     * <code>int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 2;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 2;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SeatUpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:SeatUpdateRequest)
  private static final com.cinemaoperations.SeatUpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cinemaoperations.SeatUpdateRequest();
  }

  public static com.cinemaoperations.SeatUpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SeatUpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<SeatUpdateRequest>() {
    @java.lang.Override
    public SeatUpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SeatUpdateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SeatUpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SeatUpdateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cinemaoperations.SeatUpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

